# Generated by Django 5.2.4 on 2025-07-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_project_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
